# Generated by Django 5.2.15 on 2026-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField(verbose_name='Hora de inicio')),
                ('horaTermino', models.TimeField(verbose_name='Hora de término')),
                ('orden', models.PositiveIntegerField(unique=True, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
