# Generated by Django 5.2.15 on 2026-08-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloques', '0002_rename_activo_permite_agendamiento_automatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicioJornada', models.TimeField(verbose_name='Hora de inicio de la jornada')),
                ('horaTerminoJornada', models.TimeField(verbose_name='Hora de término de la jornada')),
                ('duracionBloque', models.PositiveIntegerField(verbose_name='Duración del bloque (minutos)')),
                ('horizonteBusquedaDias', models.PositiveIntegerField(verbose_name='Horizonte de búsqueda (días)')),
                ('claveUnica', models.PositiveSmallIntegerField(default=1, editable=False, unique=True, verbose_name='Clave única (uso interno)')),
            ],
        ),
    ]
