# Generated by Django 5.2.15 on 2026-08-09 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloques', '0002_rename_activo_permite_agendamiento_automatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadBloques', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de bloques')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('horaInicio', models.TimeField(verbose_name='Hora de inicio')),
                ('horaTermino', models.TimeField(verbose_name='Hora de término')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ELIMINADA', 'Eliminada')], default='PROGRAMADA', max_length=15, verbose_name='Estado')),
                ('motivoBaja', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bloqueInicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias', to='bloques.bloquehorario', verbose_name='Bloque de inicio')),
            ],
            options={
                'ordering': ['fecha', 'horaInicio'],
            },
        ),
    ]
