# Generated by Django 5.2.15 on 2026-08-09 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiencias', '0001_initial'),
        ('causas', '0001_initial'),
        ('salas', '0002_cargar_salas_iniciales'),
        ('tipos_audiencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias', to='causas.causa', verbose_name='Causa'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias', to='salas.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='tipoAudiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias', to='tipos_audiencia.tipoaudiencia', verbose_name='Tipo de audiencia'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='usuarioCreacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó la audiencia'),
        ),
    ]
