# Generated by Django 5.2.15 on 2026-08-09 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('BAJA', 'Baja')], max_length=15, verbose_name='Acción')),
                ('valoresAnteriores', models.JSONField(blank=True, null=True, verbose_name='Valores anteriores')),
                ('valoresNuevos', models.JSONField(blank=True, null=True, verbose_name='Valores nuevos')),
                ('audiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_trazabilidad', to='audiencias.audiencia', verbose_name='Audiencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_trazabilidad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-fechaHora'],
            },
        ),
    ]
