# Generated by Django 5.2.15 on 2026-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencias', '0003_registrotrazabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='anotacion',
            field=models.TextField(blank=True, default='', verbose_name='Anotación'),
        ),
    ]
