# Generated by Django 5.2.15 on 2026-08-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0002_cargar_competencias_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAudiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('plazoMinimoDias', models.PositiveIntegerField(verbose_name='Plazo mínimo (días)')),
                ('plazoMaximoDias', models.PositiveIntegerField(verbose_name='Plazo máximo (días)')),
                ('horizonteBusquedaDias', models.PositiveIntegerField(verbose_name='Horizonte de búsqueda (días)')),
                ('tipoPlazo', models.CharField(choices=[('HABIL', 'Hábil'), ('CORRIDO', 'Corrido')], max_length=10, verbose_name='Tipo de plazo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_audiencia', to='competencias.competencia', verbose_name='Competencia')),
            ],
            options={
                'ordering': ['competencia', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('competencia', 'nombre'), name='unique_tipo_audiencia_por_competencia')],
            },
        ),
    ]
