# Generated by Django 5.2.15 on 2026-08-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_audiencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaudiencia',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveConstraint(
            model_name='tipoaudiencia',
            name='unique_tipo_audiencia_por_competencia',
        ),
        migrations.RemoveField(
            model_name='tipoaudiencia',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='tipoaudiencia',
            name='horizonteBusquedaDias',
        ),
        migrations.RemoveField(
            model_name='tipoaudiencia',
            name='plazoMaximoDias',
        ),
        migrations.RemoveField(
            model_name='tipoaudiencia',
            name='plazoMinimoDias',
        ),
        migrations.RemoveField(
            model_name='tipoaudiencia',
            name='tipoPlazo',
        ),
        migrations.AlterField(
            model_name='tipoaudiencia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
