# Generated by Django 5.2.15 on 2026-08-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0002_cargar_competencias_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rit', models.CharField(max_length=20, verbose_name='RIT')),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('caratulado', models.CharField(max_length=255, verbose_name='Carátulo')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causas', to='competencias.competencia', verbose_name='Competencia')),
            ],
            options={
                'ordering': ['rit'],
            },
        ),
    ]
