# Generated by Django 5.2.15 on 2026-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0001_initial'),
        ('competencias', '0002_cargar_competencias_iniciales'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='causa',
            constraint=models.UniqueConstraint(fields=('competencia', 'rit'), name='unique_causa_por_competencia_y_rit'),
        ),
    ]
