# Generated by Django 5.2.15 on 2026-08-21 02:20

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
