# Generated by Django 5.2.15 on 2026-09-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuarioIntentado', models.CharField(blank=True, max_length=150, verbose_name='Nombre de usuario intentado')),
                ('tipoEvento', models.CharField(choices=[('LOGIN_EXITOSO', 'Login exitoso'), ('LOGIN_FALLIDO', 'Login fallido'), ('LOGOUT', 'Logout'), ('ACCESO_DENEGADO', 'Acceso denegado')], max_length=20, verbose_name='Tipo de evento')),
                ('exitoso', models.BooleanField(verbose_name='Exitoso')),
                ('fechaHora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('direccionIp', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('rutaSolicitada', models.CharField(blank=True, max_length=255, verbose_name='Ruta solicitada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrosAcceso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-fechaHora'],
            },
        ),
    ]
