# Generated by Django 5.2.15 on 2026-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('CIERRE_TRIBUNAL', 'Cierre de tribunal'), ('MANTENCION', 'Mantención'), ('SUSPENSION_JUDICIAL', 'Suspensión judicial'), ('OTRO', 'Otro')], max_length=25, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
