# Generated by Django 5.2.15 on 2026-08-07 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0002_cargar_competencias_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10, verbose_name='Día de la semana')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_agendamiento', to='competencias.competencia', verbose_name='Competencia')),
            ],
            options={
                'ordering': ['competencia', 'diaSemana'],
                'constraints': [models.UniqueConstraint(fields=('competencia', 'diaSemana'), name='unique_regla_por_competencia_y_dia')],
            },
        ),
    ]
