# Generated by Django 5.2.15 on 2026-08-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0002_cargar_competencias_iniciales'),
        ('reglas_agendamiento', '0001_initial'),
        ('tipos_audiencia', '0002_alter_tipoaudiencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10, verbose_name='Día de la semana')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'ordering': ['competencia', 'diaSemana'],
            },
        ),
        migrations.AlterModelOptions(
            name='reglaagendamiento',
            options={'ordering': ['competencia', 'tipoAudiencia']},
        ),
        migrations.RemoveConstraint(
            model_name='reglaagendamiento',
            name='unique_regla_por_competencia_y_dia',
        ),
        migrations.RemoveField(
            model_name='reglaagendamiento',
            name='diaSemana',
        ),
        migrations.AddField(
            model_name='reglaagendamiento',
            name='plazoMaximo',
            field=models.PositiveIntegerField(default=0, verbose_name='Plazo máximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglaagendamiento',
            name='plazoMinimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Plazo mínimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglaagendamiento',
            name='tipoAudiencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_agendamiento', to='tipos_audiencia.tipoaudiencia', verbose_name='Tipo de audiencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglaagendamiento',
            name='unidadPlazo',
            field=models.CharField(choices=[('HABIL', 'Hábil'), ('CORRIDO', 'Corrido')], default='HABIL', max_length=10, verbose_name='Unidad de plazo'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reglaagendamiento',
            constraint=models.UniqueConstraint(fields=('competencia', 'tipoAudiencia'), name='unique_regla_por_competencia_y_tipo'),
        ),
        migrations.AddField(
            model_name='diaatencion',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias_atencion', to='competencias.competencia', verbose_name='Competencia'),
        ),
        migrations.AddConstraint(
            model_name='diaatencion',
            constraint=models.UniqueConstraint(fields=('competencia', 'diaSemana'), name='unique_dia_atencion_por_competencia'),
        ),
    ]
