# Generated by Django 5.2.15 on 2026-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglas_agendamiento', '0002_diaatencion_alter_reglaagendamiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaagendamiento',
            name='plazoMaximo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo máximo'),
        ),
        migrations.AlterField(
            model_name='reglaagendamiento',
            name='plazoMinimo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo mínimo'),
        ),
    ]
